spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI:http://localhost:8071}
      - optional:classpath:resilience4j-config.yml