spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
#    - native #set the spring profile associated with the backend repository (file system)
#    - vault
  cloud:
    config:
      server:
        profile-separator: ','
        #Local configuration: this locations can either of classpath or locations in the file system
        native:
          #read from a specific file system folder
          search-locations: classpath:/config
        vault:
          port: 8200
          host: ${VAULT_HOST:127.0.0.1}
          kv-version: 2
server:
  port: 8071
encrypt:
  key: ${CONFIG_SERVER_SYMMETRIC_KEY:secretkey}
logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    root: INFO